name: NodeJs
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  NPM_TOKEN: ${{secrets.NPM_TOKEN }}
  NODEJS: 16
  YARN_CACHE: "yarn-cache"

on:
  push:
    branches: [ develop, master ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ develop, master ]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ '14', '16' ]
    steps:
        - uses: actions/checkout@v3
        - name: Set yarn cache
          run: yarn config set cache-folder ${{env.YARN_CACHE}}
        - name: Setup Node.js ${{ matrix.node }}
          uses: actions/setup-node@v3.0.0
          with:
            node-version: ${{ matrix.node }}
        - name: Get yarn cache directory path
          id: yarn-cache-dir-path
          run: echo "::set-output name=dir::$(yarn cache dir)"
        - name: Cache yarn cache
          uses: actions/cache@v3
          id: cache-yarn-cache
          with:
            path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
            key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
            restore-keys: |
              ${{ runner.os }}-yarn-
        - name: Cache node_modules
          id: cache-node-modules
          uses: actions/cache@v3
          with:
            path: node_modules
            key: ${{ runner.os }}-${{ matrix.node-version }}-nodemodules-${{ hashFiles('**/yarn.lock') }}
            restore-keys: |
              ${{ runner.os }}-${{ matrix.node-version }}-nodemodules-
        - name: Install dependencies
          run: yarn install --frozen-lockfile
        - name: Run tests
          run: yarn test
        - name: Upload code coverage
          uses: codecov/codecov-action@v2.1.0
          with:
            fail_ci_if_error: true # optional (default = false)
  deploy-pages:
    needs: build
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set yarn cache
        run: yarn config set cache-folder ${{env.YARN_CACHE}}
      - name: Setup Node.js
        uses: actions/setup-node@v3.0.0
        with:
          node-version: ${{env.NODEJS}}
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: Cache yarn cache
        uses: actions/cache@v3
        id: cache-yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Cache node_modules
        id: cache-node-modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ matrix.node-version }}-nodemodules-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.node-version }}-nodemodules-
      - name: Install semantic-release dependencies
        run: yarn install --frozen-lockfile
      - name: Build package
        run: yarn build:example
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4.2.5
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: docs # The folder the action should deploy.
            
  release:
    needs: build
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set yarn cache
        run: yarn config set cache-folder ${{env.YARN_CACHE}}
      - name: Setup Node.js
        uses: actions/setup-node@v3.0.0
        with:
          node-version: ${{env.NODEJS}}
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: Cache yarn cache
        uses: actions/cache@v3
        id: cache-yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Cache node_modules
        id: cache-node-modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ matrix.node-version }}-nodemodules-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.node-version }}-nodemodules-
      - name: Install semantic-release dependencies
        run: yarn install --frozen-lockfile
      - name: Build package
        run: yarn build
      - name: Release
        run: yarn semantic-release
      
